### ISSUE TITLE
O robô consegue realmente fazer as entradas?

### ISSUE THREAD

**Issue by bbraga193** [provezano/BBot#1]
Bom dia!

Primeiramente, parabéns pelo projeto. Excelente escrita, organização e execução.
Em meus testes eu fiquei na dúvida sobre o robô estar verdadeiramente fazendo as entradas. Vi que no código tem muitas linhas comentadas. O robô já está funcional?

**Comment by provezano** [comment]
Sim. Só precisa ter paciência até as condições serem satisfeitas. Ainda estou analisando alguns momentos que ele deveria ter entrado e não entra. Acredito que casos como esse sejam decorrentes do atraso dos indicadores (bandas de bollinger e ema).
