### ISSUE TITLE
Update Time e ativos OTC

### ISSUE THREAD

**Issue by octaviodegodoy** [provezano/BBot#2]
Boa tarde, estou analisando o código. Queria entender o porque dos números primos, seria apenas para randomizar os tempos de atualização ? Poderia incluir os ativos OTC para operar nos finais de semana ? Fiz o teste aqui e deu certo . Gostaria de ajudar na melhoria do código.

**Comment by provezano** [comment]
P: "seria apenas para randomizar os tempos de atualização"
R: Sim.

P: "Poderia incluir os ativos OTC para operar nos finais de semana ?"
R: Isso é facilmente configurável no código como você deve ter descoberto. Não pretendo fazer atualizações de personalização, apenas de correção ou melhoria de performance. Fique a vontade para fazer um fork e as suas personalizações.
